version: 0.0
os: linux
files:
#  - source: Config/config.txt
#    destination: /webapps/Config
  - source: build/libs/gs-rest-service-0.1.0.jar
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
#  AfterInstall:
#    - location: Scripts/RunResourceTests.sh
#      timeout: 180
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: root
      timeout: 60
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600