version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - gradle clean
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/gs-rest-service-0.1.0.jar
    - scripts/app_start.sh
    - appspec.yml
